// Generated by gencpp from file qt_robot_interface/setting_infoResponse.msg
// DO NOT EDIT!


#ifndef QT_ROBOT_INTERFACE_MESSAGE_SETTING_INFORESPONSE_H
#define QT_ROBOT_INTERFACE_MESSAGE_SETTING_INFORESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qt_robot_interface
{
template <class ContainerAllocator>
struct setting_infoResponse_
{
  typedef setting_infoResponse_<ContainerAllocator> Type;

  setting_infoResponse_()
    : info()  {
    }
  setting_infoResponse_(const ContainerAllocator& _alloc)
    : info(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _info_type;
  _info_type info;





  typedef boost::shared_ptr< ::qt_robot_interface::setting_infoResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qt_robot_interface::setting_infoResponse_<ContainerAllocator> const> ConstPtr;

}; // struct setting_infoResponse_

typedef ::qt_robot_interface::setting_infoResponse_<std::allocator<void> > setting_infoResponse;

typedef boost::shared_ptr< ::qt_robot_interface::setting_infoResponse > setting_infoResponsePtr;
typedef boost::shared_ptr< ::qt_robot_interface::setting_infoResponse const> setting_infoResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qt_robot_interface::setting_infoResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qt_robot_interface::setting_infoResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qt_robot_interface::setting_infoResponse_<ContainerAllocator1> & lhs, const ::qt_robot_interface::setting_infoResponse_<ContainerAllocator2> & rhs)
{
  return lhs.info == rhs.info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qt_robot_interface::setting_infoResponse_<ContainerAllocator1> & lhs, const ::qt_robot_interface::setting_infoResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qt_robot_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qt_robot_interface::setting_infoResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_robot_interface::setting_infoResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_robot_interface::setting_infoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_robot_interface::setting_infoResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_robot_interface::setting_infoResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_robot_interface::setting_infoResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qt_robot_interface::setting_infoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c10fc26d5cca9a4b9114f5fc5dea9570";
  }

  static const char* value(const ::qt_robot_interface::setting_infoResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc10fc26d5cca9a4bULL;
  static const uint64_t static_value2 = 0x9114f5fc5dea9570ULL;
};

template<class ContainerAllocator>
struct DataType< ::qt_robot_interface::setting_infoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qt_robot_interface/setting_infoResponse";
  }

  static const char* value(const ::qt_robot_interface::setting_infoResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qt_robot_interface::setting_infoResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string info\n"
"\n"
;
  }

  static const char* value(const ::qt_robot_interface::setting_infoResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qt_robot_interface::setting_infoResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setting_infoResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qt_robot_interface::setting_infoResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qt_robot_interface::setting_infoResponse_<ContainerAllocator>& v)
  {
    s << indent << "info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QT_ROBOT_INTERFACE_MESSAGE_SETTING_INFORESPONSE_H
