// Generated by gencpp from file qt_robot_interface/setting_downloadResponse.msg
// DO NOT EDIT!


#ifndef QT_ROBOT_INTERFACE_MESSAGE_SETTING_DOWNLOADRESPONSE_H
#define QT_ROBOT_INTERFACE_MESSAGE_SETTING_DOWNLOADRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qt_robot_interface
{
template <class ContainerAllocator>
struct setting_downloadResponse_
{
  typedef setting_downloadResponse_<ContainerAllocator> Type;

  setting_downloadResponse_()
    : data()
    , status(false)  {
    }
  setting_downloadResponse_(const ContainerAllocator& _alloc)
    : data(_alloc)
    , status(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _data_type;
  _data_type data;

   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::qt_robot_interface::setting_downloadResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qt_robot_interface::setting_downloadResponse_<ContainerAllocator> const> ConstPtr;

}; // struct setting_downloadResponse_

typedef ::qt_robot_interface::setting_downloadResponse_<std::allocator<void> > setting_downloadResponse;

typedef boost::shared_ptr< ::qt_robot_interface::setting_downloadResponse > setting_downloadResponsePtr;
typedef boost::shared_ptr< ::qt_robot_interface::setting_downloadResponse const> setting_downloadResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qt_robot_interface::setting_downloadResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qt_robot_interface::setting_downloadResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qt_robot_interface::setting_downloadResponse_<ContainerAllocator1> & lhs, const ::qt_robot_interface::setting_downloadResponse_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qt_robot_interface::setting_downloadResponse_<ContainerAllocator1> & lhs, const ::qt_robot_interface::setting_downloadResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qt_robot_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qt_robot_interface::setting_downloadResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_robot_interface::setting_downloadResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_robot_interface::setting_downloadResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_robot_interface::setting_downloadResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_robot_interface::setting_downloadResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_robot_interface::setting_downloadResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qt_robot_interface::setting_downloadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "22c8c7d3bde9abf68f09df7d02fd2240";
  }

  static const char* value(const ::qt_robot_interface::setting_downloadResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x22c8c7d3bde9abf6ULL;
  static const uint64_t static_value2 = 0x8f09df7d02fd2240ULL;
};

template<class ContainerAllocator>
struct DataType< ::qt_robot_interface::setting_downloadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qt_robot_interface/setting_downloadResponse";
  }

  static const char* value(const ::qt_robot_interface::setting_downloadResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qt_robot_interface::setting_downloadResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string data\n"
"bool status\n"
"\n"
;
  }

  static const char* value(const ::qt_robot_interface::setting_downloadResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qt_robot_interface::setting_downloadResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setting_downloadResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qt_robot_interface::setting_downloadResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qt_robot_interface::setting_downloadResponse_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QT_ROBOT_INTERFACE_MESSAGE_SETTING_DOWNLOADRESPONSE_H
