// Generated by gencpp from file qt_robot_interface/setting_download.msg
// DO NOT EDIT!


#ifndef QT_ROBOT_INTERFACE_MESSAGE_SETTING_DOWNLOAD_H
#define QT_ROBOT_INTERFACE_MESSAGE_SETTING_DOWNLOAD_H

#include <ros/service_traits.h>


#include <qt_robot_interface/setting_downloadRequest.h>
#include <qt_robot_interface/setting_downloadResponse.h>


namespace qt_robot_interface
{

struct setting_download
{

typedef setting_downloadRequest Request;
typedef setting_downloadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setting_download
} // namespace qt_robot_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qt_robot_interface::setting_download > {
  static const char* value()
  {
    return "c2187fcc5b554d3b041641bcea605d5a";
  }

  static const char* value(const ::qt_robot_interface::setting_download&) { return value(); }
};

template<>
struct DataType< ::qt_robot_interface::setting_download > {
  static const char* value()
  {
    return "qt_robot_interface/setting_download";
  }

  static const char* value(const ::qt_robot_interface::setting_download&) { return value(); }
};


// service_traits::MD5Sum< ::qt_robot_interface::setting_downloadRequest> should match
// service_traits::MD5Sum< ::qt_robot_interface::setting_download >
template<>
struct MD5Sum< ::qt_robot_interface::setting_downloadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qt_robot_interface::setting_download >::value();
  }
  static const char* value(const ::qt_robot_interface::setting_downloadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_robot_interface::setting_downloadRequest> should match
// service_traits::DataType< ::qt_robot_interface::setting_download >
template<>
struct DataType< ::qt_robot_interface::setting_downloadRequest>
{
  static const char* value()
  {
    return DataType< ::qt_robot_interface::setting_download >::value();
  }
  static const char* value(const ::qt_robot_interface::setting_downloadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qt_robot_interface::setting_downloadResponse> should match
// service_traits::MD5Sum< ::qt_robot_interface::setting_download >
template<>
struct MD5Sum< ::qt_robot_interface::setting_downloadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qt_robot_interface::setting_download >::value();
  }
  static const char* value(const ::qt_robot_interface::setting_downloadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_robot_interface::setting_downloadResponse> should match
// service_traits::DataType< ::qt_robot_interface::setting_download >
template<>
struct DataType< ::qt_robot_interface::setting_downloadResponse>
{
  static const char* value()
  {
    return DataType< ::qt_robot_interface::setting_download >::value();
  }
  static const char* value(const ::qt_robot_interface::setting_downloadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QT_ROBOT_INTERFACE_MESSAGE_SETTING_DOWNLOAD_H
