// Generated by gencpp from file qt_robot_interface/setting_info.msg
// DO NOT EDIT!


#ifndef QT_ROBOT_INTERFACE_MESSAGE_SETTING_INFO_H
#define QT_ROBOT_INTERFACE_MESSAGE_SETTING_INFO_H

#include <ros/service_traits.h>


#include <qt_robot_interface/setting_infoRequest.h>
#include <qt_robot_interface/setting_infoResponse.h>


namespace qt_robot_interface
{

struct setting_info
{

typedef setting_infoRequest Request;
typedef setting_infoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setting_info
} // namespace qt_robot_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qt_robot_interface::setting_info > {
  static const char* value()
  {
    return "c10fc26d5cca9a4b9114f5fc5dea9570";
  }

  static const char* value(const ::qt_robot_interface::setting_info&) { return value(); }
};

template<>
struct DataType< ::qt_robot_interface::setting_info > {
  static const char* value()
  {
    return "qt_robot_interface/setting_info";
  }

  static const char* value(const ::qt_robot_interface::setting_info&) { return value(); }
};


// service_traits::MD5Sum< ::qt_robot_interface::setting_infoRequest> should match
// service_traits::MD5Sum< ::qt_robot_interface::setting_info >
template<>
struct MD5Sum< ::qt_robot_interface::setting_infoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qt_robot_interface::setting_info >::value();
  }
  static const char* value(const ::qt_robot_interface::setting_infoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_robot_interface::setting_infoRequest> should match
// service_traits::DataType< ::qt_robot_interface::setting_info >
template<>
struct DataType< ::qt_robot_interface::setting_infoRequest>
{
  static const char* value()
  {
    return DataType< ::qt_robot_interface::setting_info >::value();
  }
  static const char* value(const ::qt_robot_interface::setting_infoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qt_robot_interface::setting_infoResponse> should match
// service_traits::MD5Sum< ::qt_robot_interface::setting_info >
template<>
struct MD5Sum< ::qt_robot_interface::setting_infoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qt_robot_interface::setting_info >::value();
  }
  static const char* value(const ::qt_robot_interface::setting_infoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_robot_interface::setting_infoResponse> should match
// service_traits::DataType< ::qt_robot_interface::setting_info >
template<>
struct DataType< ::qt_robot_interface::setting_infoResponse>
{
  static const char* value()
  {
    return DataType< ::qt_robot_interface::setting_info >::value();
  }
  static const char* value(const ::qt_robot_interface::setting_infoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QT_ROBOT_INTERFACE_MESSAGE_SETTING_INFO_H
