// Generated by gencpp from file qt_robot_interface/setting_upload.msg
// DO NOT EDIT!


#ifndef QT_ROBOT_INTERFACE_MESSAGE_SETTING_UPLOAD_H
#define QT_ROBOT_INTERFACE_MESSAGE_SETTING_UPLOAD_H

#include <ros/service_traits.h>


#include <qt_robot_interface/setting_uploadRequest.h>
#include <qt_robot_interface/setting_uploadResponse.h>


namespace qt_robot_interface
{

struct setting_upload
{

typedef setting_uploadRequest Request;
typedef setting_uploadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setting_upload
} // namespace qt_robot_interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qt_robot_interface::setting_upload > {
  static const char* value()
  {
    return "ca9249eb5cbf48983e24f8f142ef641c";
  }

  static const char* value(const ::qt_robot_interface::setting_upload&) { return value(); }
};

template<>
struct DataType< ::qt_robot_interface::setting_upload > {
  static const char* value()
  {
    return "qt_robot_interface/setting_upload";
  }

  static const char* value(const ::qt_robot_interface::setting_upload&) { return value(); }
};


// service_traits::MD5Sum< ::qt_robot_interface::setting_uploadRequest> should match
// service_traits::MD5Sum< ::qt_robot_interface::setting_upload >
template<>
struct MD5Sum< ::qt_robot_interface::setting_uploadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qt_robot_interface::setting_upload >::value();
  }
  static const char* value(const ::qt_robot_interface::setting_uploadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_robot_interface::setting_uploadRequest> should match
// service_traits::DataType< ::qt_robot_interface::setting_upload >
template<>
struct DataType< ::qt_robot_interface::setting_uploadRequest>
{
  static const char* value()
  {
    return DataType< ::qt_robot_interface::setting_upload >::value();
  }
  static const char* value(const ::qt_robot_interface::setting_uploadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qt_robot_interface::setting_uploadResponse> should match
// service_traits::MD5Sum< ::qt_robot_interface::setting_upload >
template<>
struct MD5Sum< ::qt_robot_interface::setting_uploadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qt_robot_interface::setting_upload >::value();
  }
  static const char* value(const ::qt_robot_interface::setting_uploadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_robot_interface::setting_uploadResponse> should match
// service_traits::DataType< ::qt_robot_interface::setting_upload >
template<>
struct DataType< ::qt_robot_interface::setting_uploadResponse>
{
  static const char* value()
  {
    return DataType< ::qt_robot_interface::setting_upload >::value();
  }
  static const char* value(const ::qt_robot_interface::setting_uploadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QT_ROBOT_INTERFACE_MESSAGE_SETTING_UPLOAD_H
