// Generated by gencpp from file qt_nuitrack_app/Gestures.msg
// DO NOT EDIT!


#ifndef QT_NUITRACK_APP_MESSAGE_GESTURES_H
#define QT_NUITRACK_APP_MESSAGE_GESTURES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <qt_nuitrack_app/GestureInfo.h>

namespace qt_nuitrack_app
{
template <class ContainerAllocator>
struct Gestures_
{
  typedef Gestures_<ContainerAllocator> Type;

  Gestures_()
    : gestures()  {
    }
  Gestures_(const ContainerAllocator& _alloc)
    : gestures(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::qt_nuitrack_app::GestureInfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::qt_nuitrack_app::GestureInfo_<ContainerAllocator> >> _gestures_type;
  _gestures_type gestures;





  typedef boost::shared_ptr< ::qt_nuitrack_app::Gestures_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qt_nuitrack_app::Gestures_<ContainerAllocator> const> ConstPtr;

}; // struct Gestures_

typedef ::qt_nuitrack_app::Gestures_<std::allocator<void> > Gestures;

typedef boost::shared_ptr< ::qt_nuitrack_app::Gestures > GesturesPtr;
typedef boost::shared_ptr< ::qt_nuitrack_app::Gestures const> GesturesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qt_nuitrack_app::Gestures_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qt_nuitrack_app::Gestures_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qt_nuitrack_app::Gestures_<ContainerAllocator1> & lhs, const ::qt_nuitrack_app::Gestures_<ContainerAllocator2> & rhs)
{
  return lhs.gestures == rhs.gestures;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qt_nuitrack_app::Gestures_<ContainerAllocator1> & lhs, const ::qt_nuitrack_app::Gestures_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qt_nuitrack_app

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qt_nuitrack_app::Gestures_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_nuitrack_app::Gestures_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_nuitrack_app::Gestures_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_nuitrack_app::Gestures_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_nuitrack_app::Gestures_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_nuitrack_app::Gestures_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qt_nuitrack_app::Gestures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cb33e599df6d94bfd33170149d8d8cba";
  }

  static const char* value(const ::qt_nuitrack_app::Gestures_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcb33e599df6d94bfULL;
  static const uint64_t static_value2 = 0xd33170149d8d8cbaULL;
};

template<class ContainerAllocator>
struct DataType< ::qt_nuitrack_app::Gestures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qt_nuitrack_app/Gestures";
  }

  static const char* value(const ::qt_nuitrack_app::Gestures_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qt_nuitrack_app::Gestures_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#std_msgs/Header header\n"
"GestureInfo[] gestures\n"
"\n"
"================================================================================\n"
"MSG: qt_nuitrack_app/GestureInfo\n"
"#std_msgs/Header header\n"
"int32 id\n"
"string name\n"
;
  }

  static const char* value(const ::qt_nuitrack_app::Gestures_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qt_nuitrack_app::Gestures_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gestures);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gestures_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qt_nuitrack_app::Gestures_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qt_nuitrack_app::Gestures_<ContainerAllocator>& v)
  {
    s << indent << "gestures[]" << std::endl;
    for (size_t i = 0; i < v.gestures.size(); ++i)
    {
      s << indent << "  gestures[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::qt_nuitrack_app::GestureInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.gestures[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // QT_NUITRACK_APP_MESSAGE_GESTURES_H
