// Generated by gencpp from file qt_nuitrack_app/Hands.msg
// DO NOT EDIT!


#ifndef QT_NUITRACK_APP_MESSAGE_HANDS_H
#define QT_NUITRACK_APP_MESSAGE_HANDS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <qt_nuitrack_app/HandInfo.h>

namespace qt_nuitrack_app
{
template <class ContainerAllocator>
struct Hands_
{
  typedef Hands_<ContainerAllocator> Type;

  Hands_()
    : hands()  {
    }
  Hands_(const ContainerAllocator& _alloc)
    : hands(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::qt_nuitrack_app::HandInfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::qt_nuitrack_app::HandInfo_<ContainerAllocator> >> _hands_type;
  _hands_type hands;





  typedef boost::shared_ptr< ::qt_nuitrack_app::Hands_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qt_nuitrack_app::Hands_<ContainerAllocator> const> ConstPtr;

}; // struct Hands_

typedef ::qt_nuitrack_app::Hands_<std::allocator<void> > Hands;

typedef boost::shared_ptr< ::qt_nuitrack_app::Hands > HandsPtr;
typedef boost::shared_ptr< ::qt_nuitrack_app::Hands const> HandsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qt_nuitrack_app::Hands_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qt_nuitrack_app::Hands_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qt_nuitrack_app::Hands_<ContainerAllocator1> & lhs, const ::qt_nuitrack_app::Hands_<ContainerAllocator2> & rhs)
{
  return lhs.hands == rhs.hands;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qt_nuitrack_app::Hands_<ContainerAllocator1> & lhs, const ::qt_nuitrack_app::Hands_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qt_nuitrack_app

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qt_nuitrack_app::Hands_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_nuitrack_app::Hands_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_nuitrack_app::Hands_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_nuitrack_app::Hands_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_nuitrack_app::Hands_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_nuitrack_app::Hands_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qt_nuitrack_app::Hands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "633d76b336567f0906335e6cf0195299";
  }

  static const char* value(const ::qt_nuitrack_app::Hands_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x633d76b336567f09ULL;
  static const uint64_t static_value2 = 0x06335e6cf0195299ULL;
};

template<class ContainerAllocator>
struct DataType< ::qt_nuitrack_app::Hands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qt_nuitrack_app/Hands";
  }

  static const char* value(const ::qt_nuitrack_app::Hands_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qt_nuitrack_app::Hands_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#std_msgs/Header header\n"
"HandInfo[] hands\n"
"\n"
"================================================================================\n"
"MSG: qt_nuitrack_app/HandInfo\n"
"#std_msgs/Header header\n"
"int32 id\n"
"#The normalized projective (x, y) coordinate of the right hand\n"
"float32[] right_projection\n"
"#The (x,y,z) coordinate of the right hand in the world system.\n"
"float32[] right_real\n"
"bool right_click\n"
"int32 right_pressure\n"
"#The normalized projective (x, y) coordinate of the left hand\n"
"float32[] left_projection\n"
"#The (x,y,z) coordinate of the left hand in the world system.\n"
"float32[] left_real\n"
"bool left_click\n"
"int32 left_pressure\n"
;
  }

  static const char* value(const ::qt_nuitrack_app::Hands_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qt_nuitrack_app::Hands_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.hands);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Hands_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qt_nuitrack_app::Hands_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qt_nuitrack_app::Hands_<ContainerAllocator>& v)
  {
    s << indent << "hands[]" << std::endl;
    for (size_t i = 0; i < v.hands.size(); ++i)
    {
      s << indent << "  hands[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::qt_nuitrack_app::HandInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.hands[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // QT_NUITRACK_APP_MESSAGE_HANDS_H
