// Generated by gencpp from file qt_nuitrack_app/Skeletons.msg
// DO NOT EDIT!


#ifndef QT_NUITRACK_APP_MESSAGE_SKELETONS_H
#define QT_NUITRACK_APP_MESSAGE_SKELETONS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <qt_nuitrack_app/SkeletonInfo.h>

namespace qt_nuitrack_app
{
template <class ContainerAllocator>
struct Skeletons_
{
  typedef Skeletons_<ContainerAllocator> Type;

  Skeletons_()
    : skeletons()  {
    }
  Skeletons_(const ContainerAllocator& _alloc)
    : skeletons(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::qt_nuitrack_app::SkeletonInfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::qt_nuitrack_app::SkeletonInfo_<ContainerAllocator> >> _skeletons_type;
  _skeletons_type skeletons;





  typedef boost::shared_ptr< ::qt_nuitrack_app::Skeletons_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qt_nuitrack_app::Skeletons_<ContainerAllocator> const> ConstPtr;

}; // struct Skeletons_

typedef ::qt_nuitrack_app::Skeletons_<std::allocator<void> > Skeletons;

typedef boost::shared_ptr< ::qt_nuitrack_app::Skeletons > SkeletonsPtr;
typedef boost::shared_ptr< ::qt_nuitrack_app::Skeletons const> SkeletonsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qt_nuitrack_app::Skeletons_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qt_nuitrack_app::Skeletons_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qt_nuitrack_app::Skeletons_<ContainerAllocator1> & lhs, const ::qt_nuitrack_app::Skeletons_<ContainerAllocator2> & rhs)
{
  return lhs.skeletons == rhs.skeletons;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qt_nuitrack_app::Skeletons_<ContainerAllocator1> & lhs, const ::qt_nuitrack_app::Skeletons_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qt_nuitrack_app

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qt_nuitrack_app::Skeletons_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_nuitrack_app::Skeletons_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_nuitrack_app::Skeletons_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_nuitrack_app::Skeletons_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_nuitrack_app::Skeletons_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_nuitrack_app::Skeletons_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qt_nuitrack_app::Skeletons_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c9e6a0abe2b44381a0de593ee0c2c308";
  }

  static const char* value(const ::qt_nuitrack_app::Skeletons_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc9e6a0abe2b44381ULL;
  static const uint64_t static_value2 = 0xa0de593ee0c2c308ULL;
};

template<class ContainerAllocator>
struct DataType< ::qt_nuitrack_app::Skeletons_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qt_nuitrack_app/Skeletons";
  }

  static const char* value(const ::qt_nuitrack_app::Skeletons_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qt_nuitrack_app::Skeletons_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#std_msgs/Header header\n"
"SkeletonInfo[] skeletons\n"
"\n"
"================================================================================\n"
"MSG: qt_nuitrack_app/SkeletonInfo\n"
"#std_msgs/Header header\n"
"int32 id\n"
"JointInfo[] joints \n"
"\n"
"================================================================================\n"
"MSG: qt_nuitrack_app/JointInfo\n"
"#std_msgs/Header header\n"
"uint8 type\n"
"float32 confidence\n"
"float32[] real\n"
"float32[] projection\n"
"float32[] orientation\n"
;
  }

  static const char* value(const ::qt_nuitrack_app::Skeletons_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qt_nuitrack_app::Skeletons_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.skeletons);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Skeletons_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qt_nuitrack_app::Skeletons_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qt_nuitrack_app::Skeletons_<ContainerAllocator>& v)
  {
    s << indent << "skeletons[]" << std::endl;
    for (size_t i = 0; i < v.skeletons.size(); ++i)
    {
      s << indent << "  skeletons[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::qt_nuitrack_app::SkeletonInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.skeletons[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // QT_NUITRACK_APP_MESSAGE_SKELETONS_H
