// Generated by gencpp from file qt_motors_controller/set_velocityRequest.msg
// DO NOT EDIT!


#ifndef QT_MOTORS_CONTROLLER_MESSAGE_SET_VELOCITYREQUEST_H
#define QT_MOTORS_CONTROLLER_MESSAGE_SET_VELOCITYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace qt_motors_controller
{
template <class ContainerAllocator>
struct set_velocityRequest_
{
  typedef set_velocityRequest_<ContainerAllocator> Type;

  set_velocityRequest_()
    : parts()
    , velocity(0)  {
    }
  set_velocityRequest_(const ContainerAllocator& _alloc)
    : parts(_alloc)
    , velocity(0)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _parts_type;
  _parts_type parts;

   typedef uint8_t _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::qt_motors_controller::set_velocityRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qt_motors_controller::set_velocityRequest_<ContainerAllocator> const> ConstPtr;

}; // struct set_velocityRequest_

typedef ::qt_motors_controller::set_velocityRequest_<std::allocator<void> > set_velocityRequest;

typedef boost::shared_ptr< ::qt_motors_controller::set_velocityRequest > set_velocityRequestPtr;
typedef boost::shared_ptr< ::qt_motors_controller::set_velocityRequest const> set_velocityRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::qt_motors_controller::set_velocityRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::qt_motors_controller::set_velocityRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::qt_motors_controller::set_velocityRequest_<ContainerAllocator1> & lhs, const ::qt_motors_controller::set_velocityRequest_<ContainerAllocator2> & rhs)
{
  return lhs.parts == rhs.parts &&
    lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::qt_motors_controller::set_velocityRequest_<ContainerAllocator1> & lhs, const ::qt_motors_controller::set_velocityRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace qt_motors_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::qt_motors_controller::set_velocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::qt_motors_controller::set_velocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_motors_controller::set_velocityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::qt_motors_controller::set_velocityRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_motors_controller::set_velocityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::qt_motors_controller::set_velocityRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::qt_motors_controller::set_velocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "580221f6422fd270b3c14b7a16c3681e";
  }

  static const char* value(const ::qt_motors_controller::set_velocityRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x580221f6422fd270ULL;
  static const uint64_t static_value2 = 0xb3c14b7a16c3681eULL;
};

template<class ContainerAllocator>
struct DataType< ::qt_motors_controller::set_velocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "qt_motors_controller/set_velocityRequest";
  }

  static const char* value(const ::qt_motors_controller::set_velocityRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::qt_motors_controller::set_velocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# an array of robot parts and/or single joint name (e.g. ['left_arm', 'right_arm', 'HeadPitch'])\n"
"string[] parts\n"
"uint8  velocity\n"
;
  }

  static const char* value(const ::qt_motors_controller::set_velocityRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::qt_motors_controller::set_velocityRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.parts);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_velocityRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::qt_motors_controller::set_velocityRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::qt_motors_controller::set_velocityRequest_<ContainerAllocator>& v)
  {
    s << indent << "parts[]" << std::endl;
    for (size_t i = 0; i < v.parts.size(); ++i)
    {
      s << indent << "  parts[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.parts[i]);
    }
    s << indent << "velocity: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // QT_MOTORS_CONTROLLER_MESSAGE_SET_VELOCITYREQUEST_H
