// Generated by gencpp from file qt_vosk_app/speech_recognize.msg
// DO NOT EDIT!


#ifndef QT_VOSK_APP_MESSAGE_SPEECH_RECOGNIZE_H
#define QT_VOSK_APP_MESSAGE_SPEECH_RECOGNIZE_H

#include <ros/service_traits.h>


#include <qt_vosk_app/speech_recognizeRequest.h>
#include <qt_vosk_app/speech_recognizeResponse.h>


namespace qt_vosk_app
{

struct speech_recognize
{

typedef speech_recognizeRequest Request;
typedef speech_recognizeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct speech_recognize
} // namespace qt_vosk_app


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::qt_vosk_app::speech_recognize > {
  static const char* value()
  {
    return "75ea4008cc551c1370d02f534ba1f8f9";
  }

  static const char* value(const ::qt_vosk_app::speech_recognize&) { return value(); }
};

template<>
struct DataType< ::qt_vosk_app::speech_recognize > {
  static const char* value()
  {
    return "qt_vosk_app/speech_recognize";
  }

  static const char* value(const ::qt_vosk_app::speech_recognize&) { return value(); }
};


// service_traits::MD5Sum< ::qt_vosk_app::speech_recognizeRequest> should match
// service_traits::MD5Sum< ::qt_vosk_app::speech_recognize >
template<>
struct MD5Sum< ::qt_vosk_app::speech_recognizeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::qt_vosk_app::speech_recognize >::value();
  }
  static const char* value(const ::qt_vosk_app::speech_recognizeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_vosk_app::speech_recognizeRequest> should match
// service_traits::DataType< ::qt_vosk_app::speech_recognize >
template<>
struct DataType< ::qt_vosk_app::speech_recognizeRequest>
{
  static const char* value()
  {
    return DataType< ::qt_vosk_app::speech_recognize >::value();
  }
  static const char* value(const ::qt_vosk_app::speech_recognizeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::qt_vosk_app::speech_recognizeResponse> should match
// service_traits::MD5Sum< ::qt_vosk_app::speech_recognize >
template<>
struct MD5Sum< ::qt_vosk_app::speech_recognizeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::qt_vosk_app::speech_recognize >::value();
  }
  static const char* value(const ::qt_vosk_app::speech_recognizeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::qt_vosk_app::speech_recognizeResponse> should match
// service_traits::DataType< ::qt_vosk_app::speech_recognize >
template<>
struct DataType< ::qt_vosk_app::speech_recognizeResponse>
{
  static const char* value()
  {
    return DataType< ::qt_vosk_app::speech_recognize >::value();
  }
  static const char* value(const ::qt_vosk_app::speech_recognizeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // QT_VOSK_APP_MESSAGE_SPEECH_RECOGNIZE_H
